name: Backend CI/CD

on:
  push:
    branches: [ "ci-cd-pipeline" ]
  pull_request:
    branches: [ "ci-cd-pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build all microservices with Maven
        run: mvn -B clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service-registry ./service-registry
          docker push ${{ secrets.DOCKER_USERNAME }}/service-registry

          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway ./api-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway

          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./user-service
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service

          docker build -t ${{ secrets.DOCKER_USERNAME }}/match-service ./match-service
          docker push ${{ secrets.DOCKER_USERNAME }}/match-service

          docker build -t ${{ secrets.DOCKER_USERNAME }}/ticket-service ./ticket-service
          docker push ${{ secrets.DOCKER_USERNAME }}/ticket-service

          docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service ./notification-service
          docker push ${{ secrets.DOCKER_USERNAME }}/notification-service
